### ISSUE TITLE
Please add...

### ISSUE THREAD

**Issue by andretietz** [Mauin/servant#6]
- minimum required versions of rxjava and the play services
- method count

Nice idea!

**Comment by Mauin** [comment]
For the Google Play Services dependency I highly recommend using the matching version of Servant to the Play Services you're using in your application to prevent complications. In theory it might be possible, however I've seen issues regarding internal renaming/obfuscation in the Play Services that will make downgrading hard.

As for RxJava as long as you're using a 1.x version just the highest one will be used without issues that I can see. As with other RxJava libs I recommend defining the RxJava version in your application seperately.

Currently Servant has a method count of 119, however it's dependencies bring in another 20k methods (RxJava, Play Services and it's dependencies) however those will be in your application anyways, so they don't affect your dex method count.

I'll add some of these clarifications to the README as well.

**Comment by Mauin** [comment]
Closed via #8 which includes some more info in the README
