### ISSUE TITLE
Possible to sign-in?

### ISSUE THREAD

**Issue by Rainer-Lang** [Mauin/servant#9]
I use the GoogleApiClient also to sign-in and get data of the user like name and email.

`GoogleSignInOptions gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN).requestEmail().build();`
and
`mGoogleApiClient = new GoogleApiClient.Builder(this).enableAutoManage(this, this).addApi(Auth.GOOGLE_SIGN_IN_API, gso).build();`

**Comment by Mauin** [comment]
Currently this would not be supported as Servant only allows you to specify an API you want to use. I'll work on adding a solution how you can add these extras.

**Comment by Rainer-Lang** [comment]
This would be really awesome!

**Comment by Rainer-Lang** [comment]
@Mauin Could I provide further information or if I should test an alpha/snapshot....please let me know.

**Comment by Mauin** [comment]
Closed via #10.

New release with support for options will come soon.

**Comment by Mauin** [comment]
@Rainer-Lang Just released v9.6.1.1 which adds support for API options. Let me know if that works for you.

**Comment by Rainer-Lang** [comment]
@Mauin WOW, hey it's working. :)
I just did a few tests - and all seems great! Thanks a lot!!!
